version : "3.7"

services:
  myredis:
    image: redis

  myvotingapp:
    image: marcplanas/votingapp
    build:
      #dockerfile: ./src/votingapp/DockerFile
      context: ./src/votingapp
    ports:
      - 8080:80
    environment:
      REDIS: "myredis:6379"
  
  mytest:
      image: marcplanas/votingapp-test
      build:
        context: ./test
      environment:
        VOTINGAPP_HOST: "myvotingapp"
  