apiVersion: v1
kind: Pod
metadata:
    labels:
        app: myvotingapp
    name: myvotingapp
    namespace: votingapp
spec:
    containers:
        - image: paulopez/votingapp
          name : myvotingapp
          env:
          - name: REDIS
            value: "myredis:6379"
---
apiVersion: v1
kind: Pod
metadata:
    labels:
        app: myredis
    name: myredis
    namespace: votingapp
spec:
    containers:
        - image: paulopez/votingapp
          name : myvotingapp
---
apiVersion: v1
kind: Deployment
metadata:
    labels:
        app: myvotingapp
    name: vmyotingapp
    namespace: votingapp
spec:
    replicas: 2
    selector:
      labels:
        run: myvotingapp
    template:
        metadate:
            lavels:
                app:myvotingapp
        sepc:
            containers:
                - image: paulopez/myvotingapp
                name: myvotingapp
                env:

    ports:
        - nodePort: 6379
          targetPort: 6379
    selector:
        app: myredis
    type: NodePort
---

apiVersion: v1
kind: Service
metadata:
    labels:
        app: myredis
    name: votingapp
    namespace: votingapp
spec:
    ports:
        - nodePort: 6379
          targetPort: 6379
    selector:
        app: myredis
    type: NodePort
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: votingapp
    name: votingapp
    namespace: mdas
spec:
    ports:
        - nodePort: 31647
          port: 80
          targetPort: 80
    selector:
        app: myvotingapp
        env: staging
    type: NodePort

---

apiVersion: v1
kind: namespace
metadata:
    name: votingapp
spec:
    finalizers:
        - kubernetes
status:
    phase: Active
